### ISSUE TITLE
decision_tree ID3 算法，会有特征序列混乱的问题

### ISSUE THREAD

**Issue by xijianfei** [tianyunzqs/text_classifier_tasks#1]
decision_tree 的ID3算法下面，无法使用feature_list，而且使用ID3算法计算后在预测函数里面，特征序列混乱，由于例子中的数值较简单没有暴露出问题，如果使用稍微复杂一点的特征序列计算就会报错，比如把X的三组改为['a', 0, 1]这样的特征，就会发现错误。我暂时也没有完全搞清楚是哪里的问题，不知道有什么好的解决方法？

**Comment by tianyunzqs** [comment]
> decision_tree 的ID3算法下面，无法使用feature_list，而且使用ID3算法计算后在预测函数里面，特征序列混乱，由于例子中的数值较简单没有暴露出问题，如果使用稍微复杂一点的特征序列计算就会报错，比如把X的三组改为['a', 0, 1]这样的特征，就会发现错误。我暂时也没有完全搞清楚是哪里的问题，不知道有什么好的解决方法？

decision_tree 的ID3只是用来加深自己对决策树的理解，你遇到的这个问题，估计是很多边界条件没做处理。
实际应用中可用from sklearn.tree import DecisionTreeClassifier
